### ISSUE TITLE
[bug] The --uid parameter doesn't work.

### ISSUE THREAD

**Issue by robvinson** [sensepost/objection#694]
**Describe the bug**
The `--uid` flag introduced by https://github.com/sensepost/objection/pull/526 does not work. Maybe specifying a specific process ID (PID) would be an alternative?

**Expected behavior**
Attach to the application running under the UID indicated by the `--uid` flag. 

**Evidence / Logs / Screenshots**
Running a command like: `objection --uid 12 --name com.some.package start` errors out with a  stacktrace like the below. It appears that `attach()` doesn't actually support a UID parameter.

```
  File "/home/me/objection/utils/agent.py", line 250, in attach
    self.session = self.device.attach(self.pid, uid=self.config.uid)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/venv/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: Device.attach() got an unexpected keyword argument 'uid'
```

**Environment (please complete the following information):**
 - Frida Version: 16.4.8
- Objection Version: master d9c989d

**Comment by IPMegladon** [comment]
Thanks, I do not currently have an environment where I can test this, but do you mind checking if https://github.com/sensepost/objection/pull/526#issuecomment-2255211875 works within your environment in order to narrow down where the issue might be.
